### PR TITLE
plumerise + sfxdata feature

### PR DESCRIPTION
**Pull request by jsbamboo**
[major] 
- Merge new feature branch [jzhang/atm/CAfire-datasfx] to [tangq/atm/CAfire-dev] based on Ziming's PR (https://github.com/jsbamboo/E3SM/pull/1) and [BRC-RRM] branch locally on LC.
- Tests: /p/lustre1/E3SMfire/zhang73/E3SM_simulations/tst2G.datasfx.BRC_UCI.CArrm_E3SM_CAfire_dev.amip.nudge.ruby/tests/

[minor] 
- Cherry-pick some dycore variable output from oksanaguba's commits

### CODE REVIEW

**Comment by jsbamboo** [comment]
@tangq @keziming please review changes and merge it

**Comment by keziming** [comment]
I have a PR before this merge. Could we merge my PR first (plume) and then adding new development (SFX). I feel we adding both developments in one merge is not a prudential move.

**Comment by jsbamboo** [comment]
@keziming, I send this PR today because Qi suggested to merge our branches locally using command lines + tests as we did in the past 3 weeks, instead of using the website button (please see the comments in your PR). So, I don't think I have the permission to directly merge your PR using the website setting; if so, we will have to re-split our branches again, right?

You can see that all of our commits are kept in their original format and IDs. So, I don't see the actual difference of those two methods, while the command-line merge can let us do tests before make a PR.

If you have any concern, I don't mind you do the local-merge commands again in your LC repo, and then request a new PR to merge on your end. I will delete this PR then.

**Review by tangq — APPROVED** [review]
@jsbamboo , the code changes look good to me. Go ahead and merge it.

Regarding the other PR #1 , it shouldn't affect this one. You may merge that one first and then this one (resolve conflicts if needed). The reason why I suggested using command line is to keep a better history log than the web-based method.

**Comment by jsbamboo** [comment]
@tangq Thanks for the clarification. Just merged Ziming's PR and this one in turn into [tangq/atm/CAfire-dev] as you suggested. There was no conflict.

**Pull request merged**
